### ISSUE TITLE
minor corrections in Readme

### ISSUE THREAD

**Issue by anishcr** [fermyon/advent-of-spin#11]
readme has the following

```
Challenges will be added every Monday and Friday morning (9am CET)

[Challenge 1](https://github.com/fermyon/advent-of-spin/blob/main/CHALLENGE-1/README.md)
[Challenge 2](https://github.com/fermyon/advent-of-spin/blob/main/CHALLENGE-2/README.md)
[Challenge 3](https://github.com/fermyon/advent-of-spin/blob/main/CHALLENGE-3/README.md)
Challenge 4: Coming On Dec 16th at 10am CET

```

Challenge 4 was already uploaded on 12 December.

The top line says challenges will be added at 9am CET, while for Challenge 4 it says 10am CET..

**Comment by rawkode** [comment]
Fixed. Thank you

**Comment by anishcr** [comment]
After seeing that there is no submission for Challenge 5 released today, i thought Advent of Spin is over.

Happy to see in the Readme that there is going to be a Challenge 6 and 7 in the coming weeks.
